<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;
use Doctrine\ORM\QueryBuilder;

/**
 * AksesorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AksesorisRepository extends \Doctrine\ORM\EntityRepository
{
    private $alias = 'acc';

    public function query(QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder;
    }

    public function queryByKendaraanId($kendaraanId, QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.kendaraan', ':kendaraanId'))
            ->setParameter(':kendaraanId', $kendaraanId);
    }

    public function queryAktif(QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.aktif', ':aktif'))
            ->setParameter(':aktif', true);
    }

    public function queryById($id, QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.id', ':id'))
            ->setParameter(':id', $id);
    }

    public function queryOrderByNamaASC(QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->addOrderBy($this->alias . '.nama', 'ASC');
    }

    public function findAktifBySlugKategoriAndSlugKendaraanAndSlug($slug, $slug1, $slug2)
    {
        $queryBuilder = $this->createQueryBuilder($this->alias);

        return $queryBuilder
            ->leftJoin($this->alias . '.kendaraan', 'kendaraan', Join::WITH,
                $queryBuilder->expr()->eq('kendaraan.aktif', 1)
            )
            ->leftJoin('kendaraan.kategori', 'kategori', Join::WITH,
                $queryBuilder->expr()->eq('kategori.aktif', 1)
            )
            ->andWhere($queryBuilder->expr()->eq($this->alias . '.slug', ":slug2"))
            ->andWhere($queryBuilder->expr()->eq('kategori.slug', ":slug"))
            ->andWhere($queryBuilder->expr()->eq('kendaraan.slug', ":slug1"))
            ->andWhere($queryBuilder->expr()->eq('kategori.aktif', true))
            ->andWhere($queryBuilder->expr()->eq('kendaraan.aktif', true))
            ->setParameter(":slug", $slug)
            ->setParameter(":slug1", $slug1)
            ->setParameter(":slug2", $slug2)
            ->andWhere($queryBuilder->expr()->eq($this->alias . '.aktif', true))
            ->getQuery()
            ->getOneOrNullResult();
    }
}
