<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * ArtikelEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtikelEmailRepository extends \Doctrine\ORM\EntityRepository
{
    private $alias = 'artikelEmail';

    public function createQB(QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
            $queryBuilder = $queryBuilder->innerJoin("$this->alias.emailSubscribe", "emailSubscribe");
        }

        return $queryBuilder;
    }

    public function query(QueryBuilder $queryBuilder = null)
    {
        $queryBuilder = $this->createQB($queryBuilder);

        return $queryBuilder;
    }

    public function queryById($id, QueryBuilder $queryBuilder = null)
    {
        $queryBuilder = $this->createQB($queryBuilder);

        return $queryBuilder->andWhere($queryBuilder->expr()->eq("$this->alias.id", ':id'))
            ->setParameter(':id', $id);
    }

    public function queryByArtikelId($artikelId, QueryBuilder $queryBuilder = null)
    {
        $queryBuilder = $this->createQB($queryBuilder);

        return $queryBuilder->andWhere($queryBuilder->expr()->eq("$this->alias.artikel", ':artikelId'))
            ->setParameter(':artikelId', $artikelId);
    }

    public function queryBlastedArray(QueryBuilder $queryBuilder = null)
    {
        $queryBuilder = $this->createQB($queryBuilder);

        return $queryBuilder->select([
            "emailSubscribe.email"
        ]);
    }
}
