<?php

namespace AppBundle\Repository;

use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\QueryBuilder;

/**
 * BookingServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingServiceRepository extends \Doctrine\ORM\EntityRepository
{
    private $alias = 'bookser';

    public function query(QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder;
    }

    public function queryById($id, QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.id', ':id'))
            ->setParameter(':id', $id);
    }

    public function queryByDateRange($startDate, $endDate, QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder
            ->andWhere($queryBuilder->expr()->gte($this->alias . ".tanggalWaktu", ':createdAtUp'))
            ->andWhere($queryBuilder->expr()->lte($this->alias . ".tanggalWaktu", ':createdAtDown'))
            ->setParameter(':createdAtUp', date('Y-m-d 00:00:00', strtotime($startDate)))
            ->setParameter(':createdAtDown', date('Y-m-d 23:59:59', strtotime($endDate)))
            ->addOrderBy($this->alias . '.tanggalWaktu', Criteria::DESC);
    }

    public function queryByDealerId($dealerId, QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder
            ->andWhere($queryBuilder->expr()->gte($this->alias . ".dealer", ':dealerId'))
            ->setParameter(':dealerId', $dealerId);
    }
}
