<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;
use Doctrine\ORM\QueryBuilder;

/**
 * KendaraanWarnaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KendaraanWarnaRepository extends \Doctrine\ORM\EntityRepository
{
    private $alias = 'kndWrn';

    public function query(QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder;
    }

    public function queryByKendaraanId($kendaraanId, QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.kendaraan', ':kendaraanId'))
            ->setParameter(':kendaraanId', $kendaraanId);
    }

    public function queryById($id, QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.id', ':id'))
            ->setParameter(':id', $id);
    }

    public function findAktifBySlugKategoriAndSlugKendaraanAndId($slug, $slug1, $warnaId)
    {
        $queryBuilder = $this->createQueryBuilder($this->alias);

        return $queryBuilder
            ->leftJoin($this->alias . '.kendaraan', 'kendaraan', Join::WITH,
                $queryBuilder->expr()->eq('kendaraan.aktif', 1)
            )
            ->leftJoin('kendaraan.kategori', 'kategori', Join::WITH,
                $queryBuilder->expr()->eq('kategori.aktif', 1)
            )
            ->andWhere($queryBuilder->expr()->eq('kendaraan.slug', ":slug1"))
            ->andWhere($queryBuilder->expr()->eq('kategori.slug', ":slug"))
            ->andWhere($queryBuilder->expr()->eq('kategori.aktif', true))
            ->andWhere($queryBuilder->expr()->eq($this->alias . '.id', ':warnaId'))
            ->setParameter(":slug", $slug)
            ->setParameter(":slug1", $slug1)
            ->setParameter(":warnaId", $warnaId)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
