<?php

namespace AppBundle\Repository;

use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Query\Expr\Join;
use Doctrine\ORM\QueryBuilder;

/**
 * KendaraanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KendaraanRepository extends \Doctrine\ORM\EntityRepository
{
    private $alias = 'kndraan';

    public function query(QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder;
    }

    public function queryAktif(QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.aktif', ':aktif'))
            ->setParameter(':aktif', true);
    }

    public function queryByKategoriId($kategoriId, QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.kategori', ':kategoriId'))
            ->setParameter(':kategoriId', $kategoriId);
    }

    public function queryById($id, QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.id', ':id'))
            ->setParameter(':id', $id);
    }

    public function queryOrderByKategoriAndNamaASC(QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder
            ->leftJoin($this->alias . '.kategori', 'kategori')
            ->addOrderBy('kategori.nama', Criteria::ASC)
            ->addOrderBy($this->alias . '.nama', Criteria::ASC);
    }

    public function findAktifBySlugKategoriAndSlug($slug, $slug1)
    {
        $queryBuilder = $this->createQueryBuilder($this->alias);

        return $queryBuilder
            ->leftJoin($this->alias . '.kategori', 'kategori', Join::WITH,
                $queryBuilder->expr()->eq('kategori.aktif', 1)
            )
            ->andWhere($queryBuilder->expr()->eq($this->alias . '.slug', ":slug1"))
            ->andWhere($queryBuilder->expr()->eq('kategori.slug', ":slug"))
            ->andWhere($queryBuilder->expr()->eq('kategori.aktif', true))
            ->setParameter(":slug", $slug)
            ->setParameter(":slug1", $slug1)
            ->andWhere($queryBuilder->expr()->eq($this->alias . '.aktif', 1))
            ->getQuery()
            ->getOneOrNullResult();
    }
}
