<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;
use Doctrine\ORM\QueryBuilder;

/**
 * PartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartRepository extends \Doctrine\ORM\EntityRepository
{
    private $alias = 'prt';

    public function query(QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder;
    }

    public function queryAktif(QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.aktif', ':aktif'))
            ->setParameter(':aktif', true);
    }

    public function queryById($id, QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.id', ':id'))
            ->setParameter(':id', $id);
    }

    public function queryByKategoriPartId($kategoriPartId, QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.kategoriPart', ':kategoriPartId'))
            ->setParameter(':kategoriPartId', $kategoriPartId);
    }

    public function queryOrderByNamaASC(QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->addOrderBy($this->alias . '.nama', 'ASC');
    }

    public function findAktifBySlugKategoriAndSlug($slug, $slug1)
    {
        $queryBuilder = $this->createQueryBuilder($this->alias);

        return $queryBuilder
            ->leftJoin($this->alias . '.kategoriPart', 'kategoriPart', Join::WITH,
                $queryBuilder->expr()->eq('kategoriPart.aktif', 1)
            )
            ->andWhere($queryBuilder->expr()->eq($this->alias . '.slug', ":slug1"))
            ->andWhere($queryBuilder->expr()->eq('kategoriPart.slug', ":slug"))
            ->andWhere($queryBuilder->expr()->eq('kategoriPart.aktif', true))
            ->setParameter(":slug", $slug)
            ->setParameter(":slug1", $slug1)
            ->andWhere($queryBuilder->expr()->eq($this->alias . '.aktif', 1))
            ->getQuery()
            ->getOneOrNullResult();
    }
}
