<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends \Doctrine\ORM\EntityRepository
{
    private $alias = 'stt';

    public function queryFindById($id, QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.id', ':id'))
            ->setParameter(':id', $id);
    }

    public function queryFindBySettingKey($settingKey, QueryBuilder $queryBuilder = null)
    {
        if (is_null($queryBuilder)) {
            $queryBuilder = $this->createQueryBuilder($this->alias);
        }

        return $queryBuilder->andWhere($queryBuilder->expr()->eq($this->alias . '.settingKey', ':settingKey'))
            ->setParameter(':settingKey', $settingKey);
    }
}
